# Generated by Django 5.0.6 on 2024-06-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_categories_tasks_category_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
