# Generated by Django 5.0.6 on 2024-06-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
