# Generated by Django 5.0.6 on 2024-06-19 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.category'),
        ),
    ]
