# Generated by Django 5.0.6 on 2024-06-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_agregue_usuario_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='tipoUsuario',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('TRABAJADOR', 'TRABAJADOR')], db_column='tipo_usuario', default='ADMIN', max_length=100),
        ),
    ]
