# Generated by Django 5.0.6 on 2024-06-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_product_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
