# Generated by Django 5.0.6 on 2024-06-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
