# Generated by Django 5.0.6 on 2024-06-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
